STAGE: ${sls:stage}
REGION: us-east-1
ACCOUNT_ID: 972210179301
SERVICE: ${self:service}
VERSION: ${file(./package.json):version}
BCRYPT_SALT_ROUNDS: 10
COGNITO_URL: https://cognito-idp.us-east-1.amazonaws.com
COGNITO_CLIENT_ID: 5t2ev7jjncg5cgn7vaq6vpm6dg
COGNITO_CLIENT_SECRET: 4q5te8k161eppget5ffnqlgdsf6kq00stm07tj256um2bt5gc5n
RESEND_MAIL_API_KEY: re_FsEgzdsJ_DNWTFiy41QSU3cXEaHpzW5dZ
COGNITO_USER_POOL_ID: 1_HgPECUwQR

USERS_TABLE_NAME: ${self:custom.USERS_TABLE_NAME.${sls:stage}}
PROFILES_TABLE_NAME: ${self:custom.PROFILES_TABLE_NAME.${sls:stage}}
PROFILE_BUCKET_NAME: ${self:custom.PROFILE_BUCKET_NAME.${sls:stage}}