services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack_data:/var/lib/localstack

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb_admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      HOST: 0.0.0.0
      PORT: 8001
    depends_on:
      - localstack

volumes:
  localstack_data:
