service: ${sls:stage}-${file(./package.json):name}
configValidationMode: error
deprecationNotificationMode: error
useDotenv: true

package:
  patterns:
    - "!./**"
    - "dist/**/handlers/*.js"

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-1
  timeout: 30
  versionFunctions: false
  stage: ${opt:stage, 'dev'}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "stepfunctions:*"
            - "logs:*"
            - "s3:*"
            - "rekognition:*"
            - "bedrock:*"
            - "dynamodb:*"
            - "textract:*"
            - "sqs:*"
            - "events:*"
            - "states:*"
          Resource: "*"

  stackTags:
    department: x.xxxxxxxx
    squad: x.xxxxxxxx
    projectName: x.xxxxxxxx
    project: IFKPass backend
    stage: ${sls:stage}
    env: ${opt:stage, 'dev'}
    version: ${file(./package.json):version}
    

custom: ${file(ymls/custom.yml)}
functions: ${self:custom.functions}
resources: ${self:custom.resources}